### ISSUE TITLE
Small crash :-)

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#19]
Came when i did play around with add menu in acp and did delete the menu i did make i think :-)
```
[16-Mar-2016 07:36:00 UTC] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "./cache/production/twig/23/2337e46bf2d1400fc9ef38f57d52e3847dc3b4b83aaee0346597a80948af070f.php".' in C:\wamp64\www\phpBB3\vendor\twig\twig\lib\Twig\Cache\Filesystem.php:82
Stack trace:
#0 C:\wamp64\www\phpBB3\vendor\twig\twig\lib\Twig\Environment.php(400): Twig_Cache_Filesystem->write('./cache/product...', '<?php\n\n/* @blit...')
#1 C:\wamp64\www\phpBB3\phpbb\template\twig\environment.php(275): Twig_Environment->loadTemplate('@blitze_sitemak...', NULL)
#2 C:\wamp64\www\phpBB3\vendor\twig\twig\lib\Twig\Environment.php(403) : eval()'d code(193): phpbb\template\twig\environment->loadTemplate('@blitze_sitemak...')
#3 C:\wamp64\www\phpBB3\vendor\twig\twig\lib\Twig\Template.php(381): __TwigTemplate_770dfcbdfe3e2351c7f461959aa3c12801a3edfc50f3c7bcda4198f11a77b595->doDisplay(Array, Array)
#4 C:\wamp64\www\phpBB3\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#5 C:\wamp64\www\phpBB3\cach in C:\wamp64\www\phpBB3\vendor\twig\twig\lib\Twig\Template.php on line 396
```

**Comment by blitze** [comment]
Is this reproducible? Or did it just happen they one time?

**Comment by Sippan-66** [comment]
i have test to reproduct it but i can't

**Comment by blitze** [comment]
Yeah  it looks like it was a one time glitch with the phpbb cache system.  If you run into this again, please reopen this issue.

Btw, thanks for the great work you've been doing testing out this extension
