### ISSUE TITLE
phpBB 3.3: Site got corrupted

### ISSUE THREAD

**Issue by tanmoy30** [blitze/phpBB-ext-sitemaker#61]
On enabling this, the site frontend is showing only this:

Fatal error: Uncaught Error: Class 'Urodoz\Truncate\TruncateService' not found in C:\xampp\htdocs\phpBB3\cache\production\container_4335734bbdd20f586549a504dff5f80c.php:1481 Stack trace: #0 C:\xampp\htdocs\phpBB3\vendor\symfony\dependency-injection\Container.php(306): phpbb_cache_container->getBlitze_Sitemaker_Block_ForumTopicsService() #1 C:\xampp\htdocs\phpBB3\phpbb\di\service_collection.php(57): Symfony\Component\DependencyInjection\Container->get('blitze.sitemake...') #2 C:\xampp\htdocs\phpBB3\phpbb\di\service_collection_iterator.php(44): phpbb\di\service_collection->offsetGet('blitze.sitemake...') #3 C:\xampp\htdocs\phpBB3\ext\blitze\sitemaker\services\blocks\factory.php(45): phpbb\di\service_collection_iterator->current() #4 C:\xampp\htdocs\phpBB3\ext\blitze\sitemaker\services\blocks\factory.php(35): blitze\sitemaker\services\blocks\factory->register_blocks(Object(phpbb\di\service_collection)) #5 C:\xampp\htdocs\phpBB3\cache\production\container_4335734bbdd20f586549a504dff5f80c.php(1762): blitze\sitemaker\services\b in C:\xampp\htdocs\phpBB3\cache\production\container_4335734bbdd20f586549a504dff5f80c.php on line 1481

**Php details:**

PHP Version 7.3.11
Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.11

**Comment by Unixware** [comment]
my site , too stopped working after installed that ext- no big deal I  m doing the tests on a test  site - 
no way to recover even from the phpbb cli, 


```
php phpbbcli.php
PHP Fatal error:  Uncaught ReflectionException: Class Urodoz\Truncate\TruncateService does not e
xist in /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php:1174            
Stack trace:                                                                                    
#0 /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php(1174): ReflectionClas
s->__construct()                                                                                
#1 /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php(634): Symfony\Compone
nt\DependencyInjection\ContainerBuilder->createService()                                        
#2 /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php(1281): Symfony\Compon
ent\DependencyInjection\ContainerBuilder->doGet()                                               
#3 /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php(1238): Symfony\Compon
ent\DependencyInjection\ContainerBuilder->doResolveServices()                                   
#4 /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php(1149): Symfony\Compon
ent\DependencyInjection\ContainerBuilder->doResolveServices()                                   
#5 /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.php(634): Symfony\Compone
nt\DependencyInjection\C in /var/www/phpBB/vendor/symfony/dependency-injection/ContainerBuilder.
php on line 1174                           
```

**Comment by Unixware** [comment]
I think you have to follow this:

https://www.phpbb.com/customise/db/extension/phpbb_sitemaker_2/support/topic/211211
